### ISSUE TITLE
Unit tests failed when DOCKER_CERT_PATH not defined

### ISSUE THREAD

**Issue by jpthiery** [kodokojo/kodokojo#20]
As defined by @ctranxuan on Issue #16.

@ctranxuan, We develope over a docker-machine, this is why i try to retrive the `DOCKER_CERT_PATH`. I look on my Docker configuraiton class why it fail when isn't provide.

**Comment by jpthiery** [comment]
It's ssems that issue have for root cause a bad behaviour i had introduced in class [DockerSupport](https://github.com/kodokojo/commons/blob/master/src/main/java/io/kodokojo/commons/utils/docker/DockerSupport.java#L65).
I will soon merge this repository in kodokojo (#17)

**Comment by jpthiery** [comment]
@ctranxuan Could you please test again ?
Thanks.

**Comment by ctranxuan** [comment]
Hi,
This time, I've got another issue:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:02 min
[INFO] Finished at: 2016-07-11T14:55:50+00:00
[INFO] Final Memory: 15M/207M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project kodokojo: Could not resolve dependencies for project io.kodokojo:kodokojo:jar:0.1.0-SNAPSHOT: Could not find artifact io.kodokojo:kodokojo-commons-tests:jar:0.1.0-SNAPSHOT in jitpack.io (https://jitpack.io) -> [Help 1]
```

I've still used the workaround:
```export DOCKER_CERT_PATH=$PWD```

**Comment by jpthiery** [comment]
Hi,

I have merge commonsand commons-testproject in Kodo Kojo today which aren't requiered anymore.

I have forget to remove commons-test dependencies...
I remove this now from the pom.xml, running my tests and commit this.

export DOCKER_CERT_PATH may not requiered anymore too.

**Comment by jpthiery** [comment]
I commit the fix : https://github.com/kodokojo/kodokojo/blob/6c1ae496c5b0bf3607b94208f7a416b10568f769/pom.xml

**Comment by ctranxuan** [comment]
Hi,
I've got now this error message:

```
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.258:build (default) on project kodokojo: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused -> [Help 1]
```

**Comment by jpthiery** [comment]
Could you please give us your environment variables for Docker ?

**Comment by ctranxuan** [comment]
Well, I might not have any set. Could you confirm the command to show them, please?

My environment is:
- Docker version 1.11.1, build 5604cbe
- Ubuntu 15.10

**Comment by jpthiery** [comment]
Thanks for the feedback, you gave me information i need to reproduce the bug. I try on a linux engine now.

**Comment by jpthiery** [comment]
Issue occurre from the internal behavior of [docker-maven-plugin](https://github.com/spotify/docker-maven-plugin) which is not able to use docker throw the Docker Unix Socket, but only using TCP Socket.See the issue [221](https://github.com/spotify/docker-maven-plugin/issues/221) of docker-maven-pluging.

At the end of `build.sh`, we try to build docker image kodokojo/kodokojo throw a maven image which use `DOCKER_HOST`var to know how to contact the Docker Daemon.

Now, you can do that:
* Open you Docker Daemon TCP Socket adding following Docker parameter
`-H tcp://0.0.0.0:2375`
**Be aware that your Docker Deamon could be accessible to anyone!**
* Configure the `DOCKER_HOST` like this :
`export DOCKER_HOST=tcp://<YOUR PUBLIC IP>:2375`

We may not need anymore to use the `docker-maven-plugin`, so we may change soon the way to build kodokojo/kodokojo Docker image.

**Comment by jpthiery** [comment]
I would like to integrate and simplify build of docker image for kodokojo/kodokojo. This issue proved this goal isn't reached.
I change my way to build the docker image now.
Stay tuned.
